// GENERATED by tools/gen.py from sheets/*.json. Do not edit: change the sheet and run gen.py.
package dev.osl;

import java.util.List;
import java.util.Map;

public final class Sheets {
	private Sheets() {
	}

	/** Melty game_info fallout-new-vegas: one game unit = 0.0142875 m, so 1 m = 69.99 units; SkyCraft uses 70 per block for the same engine family */
	public static final double UNITS_PER_BLOCK = 70.0;
	/** universal-modder minecraft-gta5-passthrough HostLink default port */
	public static final int LINK_PORT = 25599;
	/** our own name for the frame mapping (the GTA example used Local\MCPassthroughFrame) */
	public static final String FRAME_SHM = "Local\\OSLFrame";
	/** how often Minecraft re-checks builds and reports perks */
	public static final int PERK_SYNC_SECONDS = 5;
	/** a quest chest lands this many blocks in front of the player, on the ground */
	public static final int CHEST_DISTANCE = 3;
	/** mc.y = nv.z / UNITS_PER_BLOCK + Y_OFFSET; with the taller overworld (min_y -512, height 1536) the Mojave's heights fit */
	public static final int Y_OFFSET = 64;
	/** each New Vegas worldspace (Mojave, the Strip, Freeside...) gets its own strip of the Minecraft world, this many blocks apart on X; slots are assigned in the order first visited and saved in the Minecraft world */
	public static final int WORLDSPACE_SPACING = 100000;
	/** chests.id given once when a new Minecraft world starts, so there is something to build with before the first salvage */
	public static final String STARTER_CHEST = "vault_tec_starter";
	/** on every ground reset, Minecraft removes all barrier blocks this far around the player (y +-48): earlier sessions' stray ground */
	public static final int BARRIER_SWEEP_RADIUS = 40;

	public record Stack(String item, int count) {
	}

	/** chests.json */
	public record Chest(String id, String name, List<Stack> items) {
	}

	public static final Map<String, Chest> CHESTS = Map.ofEntries(
		Map.entry("vault_tec_starter", new Chest("vault_tec_starter", "Vault-Tec Homesteading Kit", List.of(new Stack("minecraft:crafting_table", 1), new Stack("minecraft:oak_planks", 32), new Stack("minecraft:torch", 16), new Stack("minecraft:wooden_pickaxe", 1), new Stack("minecraft:wooden_axe", 1)))),
		Map.entry("doc_mitchell", new Chest("doc_mitchell", "Doc Mitchell's Care Package", List.of(new Stack("minecraft:golden_apple[custom_name=\"Stimpak\"]", 3), new Stack("minecraft:bread", 8), new Stack("minecraft:iron_pickaxe", 1), new Stack("minecraft:white_bed", 1), new Stack("minecraft:oak_door", 1)))),
		Map.entry("sunny_smiles", new Chest("sunny_smiles", "Sunny's Hunting Kit", List.of(new Stack("minecraft:bow[custom_name=\"Varmint Rifle\"]", 1), new Stack("minecraft:arrow", 32), new Stack("minecraft:cooked_beef[custom_name=\"Gecko Steak\"]", 8), new Stack("minecraft:wheat_seeds", 16), new Stack("minecraft:iron_hoe", 1)))),
		Map.entry("goodsprings_militia", new Chest("goodsprings_militia", "Goodsprings Militia Crate", List.of(new Stack("minecraft:iron_sword[custom_name=\"Machete\"]", 1), new Stack("minecraft:iron_chestplate[custom_name=\"Leather Armor\"]", 1), new Stack("minecraft:tnt[custom_name=\"Dynamite\"]", 8), new Stack("minecraft:cobblestone", 64)))),
		Map.entry("mojave_express", new Chest("mojave_express", "Mojave Express Crate", List.of(new Stack("minecraft:iron_block", 9), new Stack("minecraft:copper_block", 4), new Stack("minecraft:glass", 32), new Stack("minecraft:beacon[custom_name=\"Vault-Tec Beacon\"]", 1))))
	);

	/** quests.json */
	public record Quest(String id, String name, String chest, String message) {
	}

	public static final Map<String, Quest> QUESTS = Map.ofEntries(
		Map.entry("kick_in_the_head", new Quest("kick_in_the_head", "Ain't That a Kick in the Head", "doc_mitchell", "Doc Mitchell left you a care package.")),
		Map.entry("back_in_the_saddle", new Quest("back_in_the_saddle", "Back in the Saddle", "sunny_smiles", "Sunny Smiles packed you a hunting kit.")),
		Map.entry("ghost_town_gunfight", new Quest("ghost_town_gunfight", "Ghost Town Gunfight", "goodsprings_militia", "Goodsprings thanks you with a militia crate.")),
		Map.entry("they_went_that_a_way", new Quest("they_went_that_a_way", "They Went That-a-Way", "mojave_express", "A Mojave Express crate caught up with you."))
	);

	/** builds.json: params are the detector's settings */
	public record Build(String id, String name, String rule, Map<String, Integer> params, String perk, String hint) {
	}

	public static final List<Build> BUILDS = List.of(
		new Build("farm", "a farm", "farmland_with_crops", Map.of("radius", 12, "min", 8), "homestead", "8 tilled farmland blocks with crops planted"),
		new Build("house", "a house", "bed_door_roof", Map.of("radius", 12, "door_within", 6, "roof_within", 4), "home_sweet_home", "a bed with a door nearby and a roof over it"),
		new Build("beacon", "a beacon", "active_beacon", Map.of("radius", 16, "min_level", 1), "beacon_of_the_mojave", "a beacon on a pyramid, lit")
	);

	/** perks.json (names only: the New Vegas side applies them) */
	public record Perk(String id, String name) {
	}

	public static final Map<String, Perk> PERKS = Map.ofEntries(
		Map.entry("homestead", new Perk("homestead", "Homestead")),
		Map.entry("home_sweet_home", new Perk("home_sweet_home", "Home Sweet Home")),
		Map.entry("beacon_of_the_mojave", new Perk("beacon_of_the_mojave", "Beacon of the Mojave"))
	);
}
