#!/usr/bin/env python3
"""Generate code from the sheets: one record/struct per row, built from that row's columns.

  minecraft/src/main/java/dev/osl/Sheets.java   (Minecraft side)
  newvegas/src/sheets_gen.h                     (New Vegas plugin)
  launcher/sheets_gen.go                        (launcher: what to resolve in FalloutNV.esm)

Runs preflight first and refuses to generate if it isn't clean.
"""
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sheet(name):
    with open(os.path.join(ROOT, "sheets", name + ".json"), encoding="utf-8") as f:
        return json.load(f)["rows"]


def jstr(s):
    return json.dumps(s, ensure_ascii=False)


def cstr(s):
    return json.dumps(s, ensure_ascii=True)


HEADER = "GENERATED by tools/gen.py from sheets/*.json. Do not edit: change the sheet and run gen.py."


def java():
    out = [f"// {HEADER}", "package dev.osl;", "", "import java.util.List;", "import java.util.Map;", "",
           "public final class Sheets {", "\tprivate Sheets() {", "\t}", ""]
    for r in sheet("constants"):
        if r["side"] not in ("both", "mc"):
            continue
        t = {"int": "int", "float": "double", "string": "String"}[r["type"]]
        v = jstr(r["value"]) if r["type"] == "string" else repr(r["value"])
        out.append(f"\t/** {r['source']} */")
        out.append(f"\tpublic static final {t} {r['id']} = {v};")
    out += ["", "\tpublic record Stack(String item, int count) {", "\t}", ""]

    out += ["\t/** chests.json */", "\tpublic record Chest(String id, String name, List<Stack> items) {", "\t}", ""]
    out.append("\tpublic static final Map<String, Chest> CHESTS = Map.ofEntries(")
    rows = []
    for r in sheet("chests"):
        items = ", ".join(f"new Stack({jstr(i)}, {n})" for i, n in r["items"])
        rows.append(f"\t\tMap.entry({jstr(r['id'])}, new Chest({jstr(r['id'])}, {jstr(r['name'])}, List.of({items})))")
    out.append(",\n".join(rows))
    out += ["\t);", ""]

    out += ["\t/** quests.json */", "\tpublic record Quest(String id, String name, String chest, String message) {", "\t}", ""]
    out.append("\tpublic static final Map<String, Quest> QUESTS = Map.ofEntries(")
    out.append(",\n".join(
        f"\t\tMap.entry({jstr(r['id'])}, new Quest({jstr(r['id'])}, {jstr(r['nv_name'])}, {jstr(r['chest'])}, {jstr(r['message'])}))"
        for r in sheet("quests")))
    out += ["\t);", ""]

    out += ["\t/** builds.json: params are the detector's settings */",
            "\tpublic record Build(String id, String name, String rule, Map<String, Integer> params, String perk, String hint) {", "\t}", ""]
    out.append("\tpublic static final List<Build> BUILDS = List.of(")
    rows = []
    for r in sheet("builds"):
        params = ", ".join(f"{jstr(k)}, {v}" for k, v in r["params"].items())
        rows.append(f"\t\tnew Build({jstr(r['id'])}, {jstr(r['name'])}, {jstr(r['rule'])}, Map.of({params}), {jstr(r['perk'])}, {jstr(r['hint'])})")
    out.append(",\n".join(rows))
    out += ["\t);", ""]

    out += ["\t/** perks.json (names only: the New Vegas side applies them) */", "\tpublic record Perk(String id, String name) {", "\t}", ""]
    out.append("\tpublic static final Map<String, Perk> PERKS = Map.ofEntries(")
    out.append(",\n".join(f"\t\tMap.entry({jstr(r['id'])}, new Perk({jstr(r['id'])}, {jstr(r['name'])}))" for r in sheet("perks")))
    out += ["\t);", "}", ""]
    path = os.path.join(ROOT, "minecraft/src/main/java/dev/osl/Sheets.java")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    return path


def cpp():
    out = [f"// {HEADER}", "#pragma once", "#include <cstdint>", "", "namespace sheets {", ""]
    for r in sheet("constants"):
        if r["side"] not in ("both", "nv"):
            continue
        if r["type"] == "string":
            out.append(f"constexpr const char* {r['id']} = {cstr(r['value'])};")
        elif r["type"] == "float":
            out.append(f"constexpr float {r['id']} = {float(r['value'])}f;")
        else:
            out.append(f"constexpr int {r['id']} = {r['value']};")
    for r in sheet("hooks"):
        if r["side"] == "nv" and r["kind"] == "address" and r["value"].startswith("0x"):
            out.append(f"constexpr uint32_t ADDR_{r['id'].upper()} = {r['value']};  // {r['target']}")
    out.append("")

    out += ["// keys.json", "struct Key { int code; const char* name; bool buildOnly; const char* action; };",
            "constexpr Key KEYS[] = {"]
    out += [f"\t{{{r['nv_code']}, {cstr(r['key_name'])}, {'true' if r['mode'] == 'build' else 'false'}, {cstr(r['mc_action'])}}},"
            for r in sheet("keys")]
    out += ["};", ""]

    out += ["// loot.json", "struct Give { const char* item; int count; };",
            "struct Loot { const char* id; const char* nvName; Give gives[4]; int giveCount; const char* flavour; };",
            "constexpr Loot LOOT[] = {"]
    for r in sheet("loot"):
        if len(r["gives"]) > 4:
            raise SystemExit(f"loot.{r['id']}: at most 4 gives")
        gv = ", ".join(f"{{{cstr(i)}, {n}}}" for i, n in r["gives"])
        out.append(f"\t{{{cstr(r['id'])}, {cstr(r['nv_name'])}, {{{gv}}}, {len(r['gives'])}, {cstr(r['flavour'])}}},")
    out += ["};", ""]

    out += ["// perks.json", "struct PerkItem { const char* nvName; int count; };",
            "struct Perk { const char* id; const char* name; bool daily; PerkItem items[4]; int itemCount; const char* actorValue; int avAmount; const char* message; };",
            "constexpr Perk PERKS[] = {"]
    for r in sheet("perks"):
        items = r["nv_items"] or []
        it = ", ".join(f"{{{cstr(n)}, {c}}}" for n, c in items) or "{nullptr, 0}"
        av = r["actor_value"] or [None, 0]
        avs = cstr(av[0]) if av[0] else "nullptr"
        out.append(f"\t{{{cstr(r['id'])}, {cstr(r['name'])}, {'true' if r['kind'] == 'daily' else 'false'}, {{{it}}}, {len(items)}, {avs}, {av[1]}, {cstr(r['message'])}}},")
    out += ["};", ""]

    out += ["// quests.json", "struct Quest { const char* id; const char* nvName; };", "constexpr Quest QUESTS[] = {"]
    out += [f"\t{{{cstr(r['id'])}, {cstr(r['nv_name'])}}}," for r in sheet("quests")]
    out += ["};", "", "}  // namespace sheets", ""]
    path = os.path.join(ROOT, "newvegas/src/sheets_gen.h")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    return path


def go():
    names = []
    for r in sheet("loot"):
        names.append(("MISC", r["nv_name"]))
    for r in sheet("perks"):
        for n, _ in r["nv_items"] or []:
            if n != "Caps001":
                names.append(("ALCH", n))
    for r in sheet("quests"):
        names.append(("QUST", r["nv_name"]))
    out = [f"// {HEADER}", "package main", "", "// wanted: every New Vegas form the sheets name, found in FalloutNV.esm by record type and in-game name.",
           "var wanted = []wantedForm{"]
    seen = set()
    for t, n in names:
        if (t, n) in seen:
            continue
        seen.add((t, n))
        out.append(f"\t{{Type: {jstr(t)}, Name: {jstr(n)}}},")
    out += ["}", ""]
    path = os.path.join(ROOT, "launcher/sheets_gen.go")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    return path


def main():
    if subprocess.call([sys.executable, os.path.join(ROOT, "tools/preflight.py"), "--quiet"]) != 0:
        print("gen: preflight is not clean, nothing generated")
        return 1
    for p in (java(), cpp(), go()):
        print("gen: wrote " + os.path.relpath(p, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
